// Malware Behavior Catalog (MBC) v3.1 - Normalized JSON Dataset
// Source: https://github.com/MBCProject/mbc-markdown
// Note: Types are exported from ./mbc/types.ts and ./mbc/index.ts

import type { MBCData } from "./mbc/types";
import { MBC_BASE_URL } from "./mbc/types";

// Export only mbcData - types are exported from mbc/index.ts for better tree-shaking
export const mbcData: MBCData = {
  version: "v3.1",
  objectives: [
    {
      objectiveId: "OB0001",
      objectiveName: "Anti-Behavioral Analysis",
      description: "Behaviors that prevent, obstruct, or evade behavioral analysis of malware--for example, analysis done using a sandbox or debugger.",
      behaviors: [
        {
          id: "B0036",
          name: "Capture Evasion",
          description: "Malware evades memory capture and forensic analysis.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/capture-evasion.md`,
        },
        {
          id: "B0025",
          name: "Conditional Execution",
          description: "Malware only executes under specific conditions.",
          attackMapping: "T1480",
          attackUrl: "https://attack.mitre.org/techniques/T1480",
          pathToMd: `${MBC_BASE_URL}/execution/conditional-execution.md`,
          methods: [
            { id: "B0025.001", name: "Conditional on File Date" },
            { id: "B0025.002", name: "Conditional on GeoIP" },
            { id: "B0025.003", name: "Conditional on OS Version" },
            { id: "B0025.004", name: "Conditional on System Language" },
            { id: "B0025.005", name: "Environmental Keying" },
          ]
        },
        {
          id: "B0001",
          name: "Debugger Detection",
          description: "Malware detects whether it's being executed inside a debugger by checking for artifacts such as DLLs, processes, and registry keys.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/debugger-detection.md`,
          methods: [
            { id: "B0001.001", name: "API Hook Detection" },
            { id: "B0001.034", name: "Anti-debugging Instructions" },
            { id: "B0001.002", name: "CheckRemoteDebuggerPresent" },
            { id: "B0001.035", name: "Debug Flags" },
            { id: "B0001.003", name: "Handle Tracing" },
            { id: "B0001.004", name: "Interrupt 2D" },
            { id: "B0001.005", name: "IsDebuggerPresent" },
            { id: "B0001.006", name: "Memory Breakpoints" },
            { id: "B0001.007", name: "Modification of Code" },
            { id: "B0001.008", name: "NtQueryInformationProcess" },
            { id: "B0001.009", name: "OutputDebugString" },
            { id: "B0001.010", name: "Page Guard" },
            { id: "B0001.011", name: "Parent Process" },
            { id: "B0001.012", name: "Process Environment Block BeingDebugged" },
            { id: "B0001.013", name: "Process Environment Block NtGlobalFlag" },
            { id: "B0001.014", name: "Process Environment Block ProcessHeap" },
            { id: "B0001.015", name: "Process Jobs" },
            { id: "B0001.016", name: "RDTSC" },
            { id: "B0001.017", name: "Self-Debugging" },
            { id: "B0001.018", name: "Software Breakpoints" },
            { id: "B0001.019", name: "TLS Callbacks" },
            { id: "B0001.020", name: "Timing/Delay Check" },
            { id: "B0001.021", name: "Trap Flag Check" },
            { id: "B0001.022", name: "UnhandledExceptionFilter" },
            { id: "B0001.023", name: "WudfIsAnyDebuggerPresent" },
            { id: "B0001.024", name: "WudfIsKernelDebuggerPresent" },
            { id: "B0001.025", name: "WudfIsUserDebuggerPresent" },
            { id: "B0001.026", name: "SetHandleInformation" },
            { id: "B0001.027", name: "CloseHandle" },
            { id: "B0001.028", name: "Interrupt 0x41" },
            { id: "B0001.029", name: "Interrupt 0x2D" },
            { id: "B0001.030", name: "Thread Environment Block" },
            { id: "B0001.031", name: "NtSetDebugFilterState" },
            { id: "B0001.032", name: "Thread Hiding" },
            { id: "B0001.033", name: "Vectored Exception Handler" },
          ]
        },
        {
          id: "B0002",
          name: "Debugger Evasion",
          description: "Malware evades debugger detection by modifying environment or execution.",
          attackMapping: "T1622",
          attackUrl: "https://attack.mitre.org/techniques/T1622",
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/debugger-evasion.md`,
          methods: [
            { id: "B0002.001", name: "Block Interrupts" },
            { id: "B0002.002", name: "Byte Stealing" },
            { id: "B0002.003", name: "Change SizeOfImage" },
            { id: "B0002.004", name: "Direct Memory Modification" },
            { id: "B0002.005", name: "Guard Pages" },
            { id: "B0002.006", name: "Inhibit System Calls" },
            { id: "B0002.007", name: "Leverage OS Security Mechanisms" },
            { id: "B0002.008", name: "Modify PE Header" },
            { id: "B0002.009", name: "Modify Registry" },
            { id: "B0002.010", name: "NtSetInformationThread" },
            { id: "B0002.011", name: "Patch Interrupt Vector Table" },
            { id: "B0002.012", name: "Relocate API Function Code" },
            { id: "B0002.013", name: "Self Unmapping" },
            { id: "B0002.014", name: "Thread Renaming" },
            { id: "B0002.015", name: "Use Anti-debugging Interrupt" },
            { id: "B0002.016", name: "Use Interrupts" },
            { id: "B0002.017", name: "Watchdog Timer" },
          ]
        },
        {
          id: "B0003",
          name: "Dynamic Analysis Evasion",
          description: "Malware evades execution in dynamic analysis environments like sandboxes.",
          attackMapping: "T1497",
          attackUrl: "https://attack.mitre.org/techniques/T1497",
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/dynamic-analysis-evasion.md`,
          methods: [
            { id: "B0003.001", name: "Alternative Execution" },
            { id: "B0003.002", name: "Code Integrity Checks" },
            { id: "B0003.003", name: "Data Execution Prevention" },
            { id: "B0003.004", name: "Data Integrity Checks" },
            { id: "B0003.005", name: "Delayed Execution" },
            { id: "B0003.006", name: "Environmental Keying" },
            { id: "B0003.007", name: "Human User Check" },
            { id: "B0003.008", name: "Introspection Evasion" },
          ]
        },
        {
          id: "B0004",
          name: "Emulator Detection",
          description: "Malware detects emulation environments through various artifacts.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/emulator-detection.md`,
          methods: [
            { id: "B0004.001", name: "CPU Feature Check" },
            { id: "B0004.002", name: "Exception Handling" },
            { id: "B0004.003", name: "Execute Non-Emulated Code" },
            { id: "B0004.004", name: "Instruction Sequence Check" },
            { id: "B0004.005", name: "Known Signature Check" },
          ]
        },
        {
          id: "B0005",
          name: "Emulator Evasion",
          description: "Malware evades emulator environments through various techniques.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/emulator-evasion.md`,
        },
        {
          id: "B0008",
          name: "Executable Code Virtualization",
          description: "Malware uses code virtualization to make analysis difficult.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/executable-code-virtualization.md`,
        },
        {
          id: "F0015",
          name: "Hijack Execution Flow",
          description: "Malware may execute by hijacking the way operating systems run programs.",
          attackMapping: "T1574",
          attackUrl: "https://attack.mitre.org/techniques/T1574",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hijack-execution-flow.md`,
          methods: [
            { id: "F0015.006", name: "Abuse Windows Function Calls" },
            { id: "F0015.001", name: "Export Address Table Hooking" },
            { id: "F0015.003", name: "Import Address Table Hooking" },
            { id: "F0015.002", name: "Inline Patching" },
            { id: "F0015.007", name: "Procedure Hooking" },
            { id: "F0015.004", name: "Shadow System Service Dispatch Table Hooking" },
            { id: "F0015.005", name: "System Service Dispatch Table Hooking" },
          ]
        },
        {
          id: "B0006",
          name: "Memory Dump Evasion",
          description: "Malware makes memory dumping more difficult by encrypting, hooking, or obfuscating memory contents.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/memory-dump-evasion.md`,
          methods: [
            { id: "B0006.001", name: "Code Encryption in Memory" },
            { id: "B0006.002", name: "Erase PE Header" },
            { id: "B0006.003", name: "Feed Fake Information" },
            { id: "B0006.004", name: "Guard Pages" },
            { id: "B0006.005", name: "Hide Virtual Machine" },
            { id: "B0006.006", name: "Hook APIs" },
            { id: "B0006.007", name: "SizeOfImage" },
            { id: "B0006.008", name: "Tampering" },
            { id: "B0006.009", name: "Unmap Section View" },
          ]
        },
        {
          id: "B0007",
          name: "Sandbox Detection",
          description: "Malware detects sandbox environments through various system and user activity checks.",
          attackMapping: "T1497.001",
          attackUrl: "https://attack.mitre.org/techniques/T1497/001",
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/sandbox-detection.md`,
          methods: [
            { id: "B0007.001", name: "Check for Specific Files" },
            { id: "B0007.002", name: "Check for Specific Modules" },
            { id: "B0007.003", name: "Check for Specific Processes" },
            { id: "B0007.004", name: "Check for Specific Registry Keys" },
            { id: "B0007.005", name: "Check for Specific Window Names" },
            { id: "B0007.006", name: "Check Number of Processors" },
            { id: "B0007.007", name: "Check Physical Memory Size" },
            { id: "B0007.008", name: "Check Screen Resolution" },
            { id: "B0007.009", name: "Check System Uptime" },
            { id: "B0007.010", name: "Check Usable Memory Size" },
            { id: "B0007.011", name: "Human User Check" },
            { id: "B0007.012", name: "Product Key/ID Check" },
            { id: "B0007.013", name: "Time Bomb" },
            { id: "B0007.014", name: "Check Username" },
          ]
        },
        {
          id: "F0001",
          name: "Software Packing",
          description: "Malware uses software packing to compress or encrypt code to hinder analysis.",
          attackMapping: "T1027.002",
          attackUrl: "https://attack.mitre.org/techniques/T1027/002",
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/software-packing.md`,
        },
        {
          id: "B0009",
          name: "Virtual Machine Detection",
          description: "Malware detects virtual machine environments through various artifacts.",
          attackMapping: "T1497",
          attackUrl: "https://attack.mitre.org/techniques/T1497",
          pathToMd: `${MBC_BASE_URL}/anti-behavioral-analysis/virtual-machine-detection.md`,
          methods: [
            { id: "B0009.001", name: "Check for Specific Hardware" },
            { id: "B0009.002", name: "Check for Specific MAC Address" },
            { id: "B0009.003", name: "Check for Specific Registry Keys" },
            { id: "B0009.004", name: "Check for Specific Running Processes" },
            { id: "B0009.005", name: "Check for Specific Running Services" },
            { id: "B0009.006", name: "CPUID Check" },
            { id: "B0009.007", name: "Guest Addition Check" },
            { id: "B0009.008", name: "Instruction Testing" },
            { id: "B0009.009", name: "Known Signature Check" },
            { id: "B0009.010", name: "Modern Bochs Check" },
            { id: "B0009.011", name: "SGDT/SLDT/SIDT" },
            { id: "B0009.012", name: "STR" },
            { id: "B0009.013", name: "Timing Attack" },
            { id: "B0009.014", name: "WMI Checks" },
          ]
        },
      ]
    },
    {
      objectiveId: "OB0002",
      objectiveName: "Anti-Static Analysis",
      description: "Behaviors and code characteristics that prevent or hinder static analysis of the malware. Simple static analysis identifies features such as embedded strings, header information, or file metadata. More involved static analysis involves the disassembly of the binary code.",
      behaviors: [
        {
          id: "B0010",
          name: "Call Graph Generation Evasion",
          description: "Malware makes it difficult to generate a call graph.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/call-graph-generation-evasion.md`,
        },
        {
          id: "B0012",
          name: "Disassembler Evasion",
          description: "Malware uses techniques to make disassembly more difficult.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/disassembler-evasion.md`,
          methods: [
            { id: "B0012.001", name: "Argument Obfuscation" },
            { id: "B0012.002", name: "Conditional Misdirection" },
            { id: "B0012.003", name: "Fake RETSN" },
            { id: "B0012.004", name: "Jump Instructions" },
            { id: "B0012.005", name: "Value Dependent Jumps" },
            { id: "B0012.006", name: "Variable Recomposition" },
          ]
        },
        {
          id: "B0045",
          name: "Data Flow Analysis Evasion",
          description: "Malware evades data flow analysis techniques.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/data-flow-analysis-evasion.md`,
        },
        {
          id: "B0032",
          name: "Executable Code Obfuscation",
          description: "Malware obfuscates its code to make analysis difficult.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/executable-code-obfuscation.md`,
          methods: [
            { id: "B0032.001", name: "API Hashing" },
            { id: "B0032.002", name: "Control Flow Flattening" },
            { id: "B0032.003", name: "Dead Code Insertion" },
            { id: "B0032.004", name: "Entry Point Obfuscation" },
            { id: "B0032.005", name: "Guard Pages" },
            { id: "B0032.006", name: "Import Hiding" },
            { id: "B0032.007", name: "Interleaving Code" },
            { id: "B0032.008", name: "Jump Instructions" },
            { id: "B0032.009", name: "Merged Code Sections" },
            { id: "B0032.010", name: "Packing" },
            { id: "B0032.011", name: "Packing with Encryption" },
            { id: "B0032.012", name: "Stack Strings" },
            { id: "B0032.013", name: "Symbol Stripping" },
            { id: "B0032.014", name: "XOR Encryption" },
          ]
        },
        {
          id: "B0034",
          name: "Executable Code Optimization",
          description: "Code optimization can be used to evade static analysis.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/executable-code-optimization.md`,
        },
        {
          id: "B0008",
          name: "Executable Code Virtualization",
          description: "Malware uses code virtualization to make analysis difficult.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/executable-code-virtualization.md`,
        },
        {
          id: "E1027",
          name: "Obfuscated Files or Information",
          description: "Malware obfuscates files or information to hinder analysis.",
          attackMapping: "T1027",
          attackUrl: "https://attack.mitre.org/techniques/T1027",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/obfuscated-files-or-information.md`,
        },
        {
          id: "F0001",
          name: "Software Packing",
          description: "Malware uses software packing to compress or encrypt code to hinder analysis.",
          attackMapping: "T1027.002",
          attackUrl: "https://attack.mitre.org/techniques/T1027/002",
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/software-packing.md`,
        },
      ]
    },
    {
      objectiveId: "OB0003",
      objectiveName: "Collection",
      description: "Behaviors that enable malware to identify and gather information, such as sensitive files, from a machine or network. Sources often targeted include drives, browsers, audio/video, and email. Often the malware's next objective is to exfiltrate the information gathered.",
      behaviors: [
        {
          id: "E1560",
          name: "Archive Collected Data",
          description: "Malware may collect and package (or archive) the information they have gathered from a compromised system. Once collected, the data is often compressed and encrypted into an archive file.",
          attackMapping: "T1560",
          attackUrl: "https://attack.mitre.org/techniques/T1560",
          pathToMd: `${MBC_BASE_URL}/collection/archive-collected-data.md`,
          methods: [
            { id: "E1560.m01", name: "Encoding" },
            { id: "E1560.m04", name: "Encoding - Custom Algorithm" },
            { id: "E1560.m03", name: "Encoding - Standard Algorithm" },
            { id: "E1560.m02", name: "Encryption" },
            { id: "E1560.m06", name: "Encryption - Custom Algorithm" },
            { id: "E1560.m05", name: "Encryption - Standard Algorithm" },
          ]
        },
        {
          id: "B0028",
          name: "Cryptocurrency",
          description: "Malware steals or manipulates cryptocurrency.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/collection/cryptocurrency.md`,
          methods: [
            { id: "B0028.001", name: "Clipboard Modification" },
            { id: "B0028.002", name: "Generate New Wallet" },
            { id: "B0028.003", name: "Hook Browser Helper Object" },
            { id: "B0028.004", name: "Steal Wallet Data" },
          ]
        },
        {
          id: "F0015",
          name: "Hijack Execution Flow",
          description: "Malware may execute by hijacking the way operating systems run programs. Malware alters API behavior or redirects execution (i.e., hooking) to a malicious API version.",
          attackMapping: "T1574",
          attackUrl: "https://attack.mitre.org/techniques/T1574",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hijack-execution-flow.md`,
          methods: [
            { id: "F0015.006", name: "Abuse Windows Function Calls" },
            { id: "F0015.001", name: "Export Address Table Hooking" },
            { id: "F0015.003", name: "Import Address Table Hooking" },
            { id: "F0015.002", name: "Inline Patching" },
            { id: "F0015.007", name: "Procedure Hooking" },
            { id: "F0015.004", name: "Shadow System Service Dispatch Table Hooking" },
            { id: "F0015.005", name: "System Service Dispatch Table Hooking" },
          ]
        },
        {
          id: "E1056",
          name: "Input Capture",
          description: "Malware may record user inputs, typically without the user's knowledge. This is often used to capture sensitive information such as usernames, passwords, credit card numbers, and other personal data.",
          attackMapping: "T1056",
          attackUrl: "https://attack.mitre.org/techniques/T1056",
          pathToMd: `${MBC_BASE_URL}/collection/input-capture.md`,
          methods: [
            { id: "E1056.m01", name: "Mouse Events" },
          ]
        },
        {
          id: "F0002",
          name: "Keylogging",
          description: "Malware captures user keyboard input.",
          attackMapping: "T1056.001",
          attackUrl: "https://attack.mitre.org/techniques/T1056/001",
          pathToMd: `${MBC_BASE_URL}/collection/keylogging.md`,
          methods: [
            { id: "F0002.001", name: "Application Hook" },
            { id: "F0002.002", name: "Polling" },
          ]
        },
        {
          id: "E1113",
          name: "Screen Capture",
          description: "Malware takes screen captures of the desktop. This technique is often used by cyber attackers to gather sensitive information.",
          attackMapping: "T1113",
          attackUrl: "https://attack.mitre.org/techniques/T1113",
          pathToMd: `${MBC_BASE_URL}/collection/screen-capture.md`,
          methods: [
            { id: "E1113.m01", name: "WinAPI" },
          ]
        },
      ]
    },
    {
      objectiveId: "OB0004",
      objectiveName: "Command and Control",
      description: "Behaviors that enable malware to communicate with systems such as C2 servers or bots. Malware can establish command and control with various levels of covertness, depending on system configuration and network topology.",
      behaviors: [
        {
          id: "B0030",
          name: "C2 Communication",
          description: "Malware communicates with command and control infrastructure.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/command-and-control/c2-communication.md`,
          methods: [
            { id: "B0030.001", name: "Check for Payload" },
            { id: "B0030.002", name: "Client/Server" },
            { id: "B0030.003", name: "One-Way Communication" },
            { id: "B0030.004", name: "Outbound Only" },
            { id: "B0030.005", name: "Peer to Peer" },
            { id: "B0030.006", name: "Receive Data" },
            { id: "B0030.007", name: "Send Data" },
            { id: "B0030.008", name: "Server to Client" },
          ]
        },
        {
          id: "B0031",
          name: "Domain Name Generation",
          description: "Malware generates domain names algorithmically.",
          attackMapping: "T1568.002",
          attackUrl: "https://attack.mitre.org/techniques/T1568/002",
          pathToMd: `${MBC_BASE_URL}/command-and-control/domain-name-generation.md`,
        },
        {
          id: "E1105",
          name: "Ingress Tool Transfer",
          description: "Malware downloads additional tools or code to the compromised system.",
          attackMapping: "T1105",
          attackUrl: "https://attack.mitre.org/techniques/T1105",
          pathToMd: `${MBC_BASE_URL}/command-and-control/ingress-tool-transfer.md`,
        },
      ]
    },
    {
      objectiveId: "OB0005",
      objectiveName: "Credential Access",
      description: "Behaviors to obtain credential access, allowing malware or its underlying threat actor to assume control of an account with the associated system and network permissions.",
      behaviors: [
        {
          id: "B0028",
          name: "Cryptocurrency",
          description: "Malware steals or manipulates cryptocurrency.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/collection/cryptocurrency.md`,
          methods: [
            { id: "B0028.001", name: "Clipboard Modification" },
            { id: "B0028.002", name: "Generate New Wallet" },
            { id: "B0028.003", name: "Hook Browser Helper Object" },
            { id: "B0028.004", name: "Steal Wallet Data" },
          ]
        },
        {
          id: "E1056",
          name: "Input Capture",
          description: "Malware may record user inputs, typically without the user's knowledge.",
          attackMapping: "T1056",
          attackUrl: "https://attack.mitre.org/techniques/T1056",
          pathToMd: `${MBC_BASE_URL}/collection/input-capture.md`,
          methods: [
            { id: "E1056.m01", name: "Mouse Events" },
          ]
        },
        {
          id: "F0002",
          name: "Keylogging",
          description: "Malware captures user keyboard input.",
          attackMapping: "T1056.001",
          attackUrl: "https://attack.mitre.org/techniques/T1056/001",
          pathToMd: `${MBC_BASE_URL}/collection/keylogging.md`,
          methods: [
            { id: "F0002.001", name: "Application Hook" },
            { id: "F0002.002", name: "Polling" },
          ]
        },
        {
          id: "E1113",
          name: "Screen Capture",
          description: "Malware takes screen captures of the desktop.",
          attackMapping: "T1113",
          attackUrl: "https://attack.mitre.org/techniques/T1113",
          pathToMd: `${MBC_BASE_URL}/collection/screen-capture.md`,
          methods: [
            { id: "E1113.m01", name: "WinAPI" },
          ]
        },
      ]
    },
    {
      objectiveId: "OB0006",
      objectiveName: "Defense Evasion",
      description: "Behaviors that enable malware to evade detection.",
      behaviors: [
        {
          id: "B0027",
          name: "Alternative Installation Location",
          description: "Malware installs itself in an alternative location to evade detection.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/defense-evasion/alternative-installation-location.md`,
        },
        {
          id: "F0013",
          name: "Bootkit",
          description: "Malware modifies the boot process to persist and evade detection.",
          attackMapping: "T1542.003",
          attackUrl: "https://attack.mitre.org/techniques/T1542/003",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/bootkit.md`,
        },
        {
          id: "B0037",
          name: "Bypass DEP",
          description: "Malware bypasses DEP security mechanisms.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/defense-evasion/bypass-data-execution-prevention.md`,
        },
        {
          id: "F0009",
          name: "Component Firmware",
          description: "Malware modifies component firmware to persist.",
          attackMapping: "T1542.002",
          attackUrl: "https://attack.mitre.org/techniques/T1542/002",
          pathToMd: `${MBC_BASE_URL}/persistence/component-firmware.md`,
        },
        {
          id: "B0025",
          name: "Conditional Execution",
          description: "Malware only executes under specific conditions.",
          attackMapping: "T1480",
          attackUrl: "https://attack.mitre.org/techniques/T1480",
          pathToMd: `${MBC_BASE_URL}/execution/conditional-execution.md`,
        },
        {
          id: "B0040",
          name: "Covert Location",
          description: "Malware hides in covert locations on the system.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/defense-evasion/covert-location.md`,
          methods: [
            { id: "B0040.001", name: "Alternate Data Streams" },
            { id: "B0040.002", name: "Registry" },
          ]
        },
        {
          id: "F0004",
          name: "Disable or Evade Security Tools",
          description: "Malware disables or evades security software.",
          attackMapping: "T1562",
          attackUrl: "https://attack.mitre.org/techniques/T1562",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/disable-or-evade-security-tools.md`,
        },
        {
          id: "E1564",
          name: "Hide Artifacts",
          description: "Malware hides artifacts to evade detection.",
          attackMapping: "T1564",
          attackUrl: "https://attack.mitre.org/techniques/T1564",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hide-artifacts.md`,
        },
        {
          id: "F0005",
          name: "Hidden Files and Directories",
          description: "Malware hides files and directories.",
          attackMapping: "T1564.001",
          attackUrl: "https://attack.mitre.org/techniques/T1564/001",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hidden-files-and-directories.md`,
        },
        {
          id: "F0015",
          name: "Hijack Execution Flow",
          description: "Malware may execute by hijacking the way operating systems run programs.",
          attackMapping: "T1574",
          attackUrl: "https://attack.mitre.org/techniques/T1574",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hijack-execution-flow.md`,
          methods: [
            { id: "F0015.006", name: "Abuse Windows Function Calls" },
            { id: "F0015.001", name: "Export Address Table Hooking" },
            { id: "F0015.003", name: "Import Address Table Hooking" },
            { id: "F0015.002", name: "Inline Patching" },
            { id: "F0015.007", name: "Procedure Hooking" },
            { id: "F0015.004", name: "Shadow System Service Dispatch Table Hooking" },
            { id: "F0015.005", name: "System Service Dispatch Table Hooking" },
          ]
        },
        {
          id: "F0006",
          name: "Indicator Blocking",
          description: "Malware blocks indicators of compromise from being recorded or transmitted.",
          attackMapping: "T1562.006",
          attackUrl: "https://attack.mitre.org/techniques/T1562/006",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/indicator-blocking.md`,
        },
        {
          id: "B0047",
          name: "Install Insecure or Malicious Configuration",
          description: "Malware installs insecure or malicious configuration.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/defense-evasion/install-insecure-or-malicious-configuration.md`,
        },
        {
          id: "E1112",
          name: "Modify Registry",
          description: "Malware modifies the Windows registry.",
          attackMapping: "T1112",
          attackUrl: "https://attack.mitre.org/techniques/T1112",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/modify-registry.md`,
        },
        {
          id: "E1027",
          name: "Obfuscated Files or Information",
          description: "Malware obfuscates files or information to hinder analysis.",
          attackMapping: "T1027",
          attackUrl: "https://attack.mitre.org/techniques/T1027",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/obfuscated-files-or-information.md`,
        },
        {
          id: "B0029",
          name: "Polymorphic Code",
          description: "Malware modifies its code to evade detection.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/defense-evasion/polymorphic-code.md`,
          methods: [
            { id: "B0029.001", name: "Code Transposition" },
            { id: "B0029.002", name: "Instruction Substitution" },
            { id: "B0029.003", name: "Register Reassignment" },
          ]
        },
        {
          id: "E1055",
          name: "Process Injection",
          description: "Malware injects code into processes to evade detection.",
          attackMapping: "T1055",
          attackUrl: "https://attack.mitre.org/techniques/T1055",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/process-injection.md`,
        },
        {
          id: "E1014",
          name: "Rootkit",
          description: "Malware uses rootkit techniques to hide its presence.",
          attackMapping: "T1014",
          attackUrl: "https://attack.mitre.org/techniques/T1014",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/rootkit.md`,
        },
        {
          id: "F0007",
          name: "Self Deletion",
          description: "Malware deletes itself to avoid detection.",
          attackMapping: "T1070.004",
          attackUrl: "https://attack.mitre.org/techniques/T1070/004",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/self-deletion.md`,
        },
        {
          id: "F0001",
          name: "Software Packing",
          description: "Malware uses software packing to compress or encrypt code to hinder analysis.",
          attackMapping: "T1027.002",
          attackUrl: "https://attack.mitre.org/techniques/T1027/002",
          pathToMd: `${MBC_BASE_URL}/anti-static-analysis/software-packing.md`,
        },
      ]
    },
    {
      objectiveId: "OB0007",
      objectiveName: "Discovery",
      description: "Behaviors that enable malware to gain knowledge about the system and network.",
      behaviors: [
        {
          id: "B0013",
          name: "Analysis Tool Discovery",
          description: "Malware discovers analysis tools running on the system.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/discovery/analysis-tool-discovery.md`,
        },
        {
          id: "E1010",
          name: "Application Window Discovery",
          description: "Malware discovers application windows running on the system.",
          attackMapping: "T1010",
          attackUrl: "https://attack.mitre.org/techniques/T1010",
          pathToMd: `${MBC_BASE_URL}/discovery/application-window-discovery.md`,
        },
        {
          id: "B0046",
          name: "Code Discovery",
          description: "Malware discovers its own code or code of other processes.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/discovery/code-discovery.md`,
        },
        {
          id: "E1083",
          name: "File and Directory Discovery",
          description: "Malware enumerates files and directories to discover information.",
          attackMapping: "T1083",
          attackUrl: "https://attack.mitre.org/techniques/T1083",
          pathToMd: `${MBC_BASE_URL}/discovery/file-and-directory-discovery.md`,
        },
        {
          id: "B0038",
          name: "Self Discovery",
          description: "Malware gathers information about itself.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/discovery/self-discovery.md`,
          methods: [
            { id: "B0038.001", name: "File Discovery" },
            { id: "B0038.002", name: "Module Discovery" },
          ]
        },
        {
          id: "B0014",
          name: "SMTP Connection Discovery",
          description: "Malware checks for SMTP connections.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/discovery/smtp-connection-discovery.md`,
        },
        {
          id: "E1082",
          name: "System Information Discovery",
          description: "Malware discovers detailed information about the system.",
          attackMapping: "T1082",
          attackUrl: "https://attack.mitre.org/techniques/T1082",
          pathToMd: `${MBC_BASE_URL}/discovery/system-information-discovery.md`,
        },
        {
          id: "B0043",
          name: "Taskbar Discovery",
          description: "Malware discovers information about the taskbar.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/discovery/taskbar-discovery.md`,
        },
      ]
    },
    {
      objectiveId: "OB0009",
      objectiveName: "Execution",
      description: "Behaviors that enable malware to execute code on a system to achieve a variety of goals.",
      behaviors: [
        {
          id: "E1059",
          name: "Command and Scripting Interpreter",
          description: "Malware abuses command and script interpreters to execute commands.",
          attackMapping: "T1059",
          attackUrl: "https://attack.mitre.org/techniques/T1059",
          pathToMd: `${MBC_BASE_URL}/execution/command-and-scripting-interpreter.md`,
        },
        {
          id: "B0025",
          name: "Conditional Execution",
          description: "Malware only executes under specific conditions.",
          attackMapping: "T1480",
          attackUrl: "https://attack.mitre.org/techniques/T1480",
          pathToMd: `${MBC_BASE_URL}/execution/conditional-execution.md`,
          methods: [
            { id: "B0025.001", name: "Conditional on File Date" },
            { id: "B0025.002", name: "Conditional on GeoIP" },
            { id: "B0025.003", name: "Conditional on OS Version" },
            { id: "B0025.004", name: "Conditional on System Language" },
            { id: "B0025.005", name: "Environmental Keying" },
          ]
        },
        {
          id: "B0044",
          name: "Execution Dependency",
          description: "Malware has dependencies for execution.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/execution/execution-dependency.md`,
        },
        {
          id: "E1203",
          name: "Exploitation for Client Execution",
          description: "Malware exploits software vulnerabilities for code execution.",
          attackMapping: "T1203",
          attackUrl: "https://attack.mitre.org/techniques/T1203",
          pathToMd: `${MBC_BASE_URL}/execution/exploitation-for-client-execution.md`,
        },
        {
          id: "B0023",
          name: "Install Additional Program",
          description: "Malware installs additional programs on the system.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/execution/install-additional-program.md`,
        },
        {
          id: "B0024",
          name: "Prevent Concurrent Execution",
          description: "Malware prevents concurrent execution of itself.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/execution/prevent-concurrent-execution.md`,
        },
        {
          id: "B0011",
          name: "Remote Commands",
          description: "Malware executes remote commands.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/execution/remote-commands.md`,
        },
        {
          id: "B0020",
          name: "Send Email",
          description: "Malware sends email for propagation or C2.",
          attackMapping: "T1566",
          attackUrl: "https://attack.mitre.org/techniques/T1566",
          pathToMd: `${MBC_BASE_URL}/execution/send-email.md`,
        },
        {
          id: "B0021",
          name: "Send Poisoned Text Message",
          description: "Malware sends poisoned SMS for propagation.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/execution/send-poisoned-text-message.md`,
        },
        {
          id: "E1569",
          name: "System Services",
          description: "Malware abuses system services for execution.",
          attackMapping: "T1569",
          attackUrl: "https://attack.mitre.org/techniques/T1569",
          pathToMd: `${MBC_BASE_URL}/execution/system-services.md`,
        },
        {
          id: "E1204",
          name: "User Execution",
          description: "Malware relies on user actions to execute.",
          attackMapping: "T1204",
          attackUrl: "https://attack.mitre.org/techniques/T1204",
          pathToMd: `${MBC_BASE_URL}/execution/user-execution.md`,
        },
      ]
    },
    {
      objectiveId: "OB0010",
      objectiveName: "Exfiltration",
      description: "Behaviors that enable malware to steal data from a system. This includes stored data, such as files, as well as data input into applications, such as web browsers.",
      behaviors: [
        {
          id: "E1020",
          name: "Automated Exfiltration",
          description: "Malware automatically exfiltrates collected data.",
          attackMapping: "T1020",
          attackUrl: "https://attack.mitre.org/techniques/T1020",
          pathToMd: `${MBC_BASE_URL}/exfiltration/automated-exfiltration.md`,
        },
      ]
    },
    {
      objectiveId: "OB0008",
      objectiveName: "Impact",
      description: "Behaviors that enable malware to manipulate, interrupt, or destroy systems and data.",
      behaviors: [
        {
          id: "E1510",
          name: "Clipboard Modification",
          description: "Malware modifies clipboard data.",
          attackMapping: "T1510",
          attackUrl: "https://attack.mitre.org/techniques/T1510",
          pathToMd: `${MBC_BASE_URL}/impact/clipboard-modification.md`,
        },
        {
          id: "F0009",
          name: "Component Firmware",
          description: "Malware modifies component firmware to persist or evade defenses.",
          attackMapping: "T1542.002",
          attackUrl: "https://attack.mitre.org/techniques/T1542/002",
          pathToMd: `${MBC_BASE_URL}/persistence/component-firmware.md`,
        },
        {
          id: "B0016",
          name: "Compromise Data Integrity",
          description: "Malware compromises data integrity.",
          attackMapping: "T1565.001",
          attackUrl: "https://attack.mitre.org/techniques/T1565/001",
          pathToMd: `${MBC_BASE_URL}/impact/compromise-data-integrity.md`,
        },
        {
          id: "E1485",
          name: "Data Destruction",
          description: "Malware destroys data on the target system.",
          attackMapping: "T1485",
          attackUrl: "https://attack.mitre.org/techniques/T1485",
          pathToMd: `${MBC_BASE_URL}/impact/data-destruction.md`,
        },
        {
          id: "E1486",
          name: "Data Encrypted for Impact",
          description: "Malware encrypts data to make it unusable, typically for ransom.",
          attackMapping: "T1486",
          attackUrl: "https://attack.mitre.org/techniques/T1486",
          pathToMd: `${MBC_BASE_URL}/impact/data-encrypted-for-impact.md`,
        },
        {
          id: "B0033",
          name: "Denial of Service",
          description: "Malware performs denial of service attacks.",
          attackMapping: "T1498",
          attackUrl: "https://attack.mitre.org/techniques/T1498",
          pathToMd: `${MBC_BASE_URL}/impact/denial-of-service.md`,
        },
        {
          id: "B0017",
          name: "Destroy Hardware",
          description: "Malware attempts to destroy hardware.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/impact/destroy-hardware.md`,
        },
        {
          id: "F0014",
          name: "Disk Wipe",
          description: "Malware wipes or corrupts the disk to destroy data.",
          attackMapping: "T1561",
          attackUrl: "https://attack.mitre.org/techniques/T1561",
          pathToMd: `${MBC_BASE_URL}/impact/disk-wipe.md`,
        },
        {
          id: "E1190",
          name: "Exploit Kit",
          description: "Malware uses exploit kits to target vulnerabilities.",
          attackMapping: "T1190",
          attackUrl: "https://attack.mitre.org/techniques/T1190",
          pathToMd: `${MBC_BASE_URL}/impact/exploit-kit.md`,
        },
        {
          id: "E1203",
          name: "Exploitation for Client Execution",
          description: "Malware exploits software vulnerabilities for code execution.",
          attackMapping: "T1203",
          attackUrl: "https://attack.mitre.org/techniques/T1203",
          pathToMd: `${MBC_BASE_URL}/execution/exploitation-for-client-execution.md`,
        },
        {
          id: "E1643",
          name: "Generate Traffic from Victim",
          description: "Malware generates network traffic from the victim system.",
          attackMapping: "T1643",
          attackUrl: "https://attack.mitre.org/techniques/T1643",
          pathToMd: `${MBC_BASE_URL}/impact/generate-traffic-from-victim.md`,
        },
        {
          id: "B0019",
          name: "Manipulate Network Traffic",
          description: "Malware manipulates network traffic.",
          attackMapping: "T1565.002",
          attackUrl: "https://attack.mitre.org/techniques/T1565/002",
          pathToMd: `${MBC_BASE_URL}/impact/manipulate-network-traffic.md`,
        },
        {
          id: "B0042",
          name: "Modify Hardware",
          description: "Malware modifies hardware settings.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/impact/modify-hardware.md`,
        },
        {
          id: "B0022",
          name: "Remote Access",
          description: "Malware provides remote access to the system.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/impact/remote-access.md`,
        },
        {
          id: "B0018",
          name: "Resource Hijacking",
          description: "Malware hijacks system resources like CPU or GPU.",
          attackMapping: "T1496",
          attackUrl: "https://attack.mitre.org/techniques/T1496",
          pathToMd: `${MBC_BASE_URL}/impact/resource-hijacking.md`,
          methods: [
            { id: "B0018.001", name: "Cryptojacking" },
            { id: "B0018.002", name: "Cryptomining" },
          ]
        },
        {
          id: "B0039",
          name: "Spamming",
          description: "Malware sends spam emails or messages.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/impact/spamming.md`,
        },
      ]
    },
    {
      objectiveId: "OB0011",
      objectiveName: "Lateral Movement",
      description: "Behaviors that enable malware to propagate or otherwise move through an environment. Lateral movement may be active, happening via direct machine access, or may be passive (for example, done via malicious email).",
      behaviors: [
        {
          id: "B0026",
          name: "Malicious Network Driver",
          description: "Malware installs a malicious network driver.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/persistence/malicious-network-driver.md`,
        },
        {
          id: "E1105",
          name: "Ingress Tool Transfer",
          description: "Malware transfers tools or files from an external system into the compromised environment.",
          attackMapping: "T1105",
          attackUrl: "https://attack.mitre.org/techniques/T1105",
          pathToMd: `${MBC_BASE_URL}/command-and-control/ingress-tool-transfer.md`,
        },
        {
          id: "B0020",
          name: "Send Email",
          description: "Malware sends email for propagation or C2.",
          attackMapping: "T1566",
          attackUrl: "https://attack.mitre.org/techniques/T1566",
          pathToMd: `${MBC_BASE_URL}/execution/send-email.md`,
        },
        {
          id: "B0021",
          name: "Send Poisoned Text Message",
          description: "Malware sends poisoned SMS for propagation.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/execution/send-poisoned-text-message.md`,
        },
        {
          id: "E1195",
          name: "Supply Chain Compromise",
          description: "Malware compromises the supply chain to propagate.",
          attackMapping: "T1195",
          attackUrl: "https://attack.mitre.org/techniques/T1195",
          pathToMd: `${MBC_BASE_URL}/lateral-movement/supply-chain-compromise.md`,
        },
      ]
    },
    {
      objectiveId: "OB0012",
      objectiveName: "Persistence",
      description: "Behaviors that enable malware to remain on a system regardless of system events, such as reboots.",
      behaviors: [
        {
          id: "F0013",
          name: "Bootkit",
          description: "Malware modifies the boot process for persistence.",
          attackMapping: "T1542.003",
          attackUrl: "https://attack.mitre.org/techniques/T1542/003",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/bootkit.md`,
        },
        {
          id: "F0009",
          name: "Component Firmware",
          description: "Malware modifies component firmware to persist or evade defenses.",
          attackMapping: "T1542.002",
          attackUrl: "https://attack.mitre.org/techniques/T1542/002",
          pathToMd: `${MBC_BASE_URL}/persistence/component-firmware.md`,
        },
        {
          id: "E1564",
          name: "Hide Artifacts",
          description: "Malware hides artifacts to evade detection.",
          attackMapping: "T1564",
          attackUrl: "https://attack.mitre.org/techniques/T1564",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hide-artifacts.md`,
        },
        {
          id: "F0005",
          name: "Hidden Files and Directories",
          description: "Malware hides files and directories.",
          attackMapping: "T1564.001",
          attackUrl: "https://attack.mitre.org/techniques/T1564/001",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hidden-files-and-directories.md`,
        },
        {
          id: "F0015",
          name: "Hijack Execution Flow",
          description: "Malware may execute by hijacking the way operating systems run programs.",
          attackMapping: "T1574",
          attackUrl: "https://attack.mitre.org/techniques/T1574",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hijack-execution-flow.md`,
          methods: [
            { id: "F0015.006", name: "Abuse Windows Function Calls" },
            { id: "F0015.001", name: "Export Address Table Hooking" },
            { id: "F0015.003", name: "Import Address Table Hooking" },
            { id: "F0015.002", name: "Inline Patching" },
            { id: "F0015.007", name: "Procedure Hooking" },
            { id: "F0015.004", name: "Shadow System Service Dispatch Table Hooking" },
            { id: "F0015.005", name: "System Service Dispatch Table Hooking" },
          ]
        },
        {
          id: "B0047",
          name: "Install Insecure or Malicious Configuration",
          description: "Malware installs insecure or malicious configuration.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/defense-evasion/install-insecure-or-malicious-configuration.md`,
        },
        {
          id: "F0010",
          name: "Kernel Modules and Extensions",
          description: "Malware loads or modifies kernel modules for persistence.",
          attackMapping: "T1547.006",
          attackUrl: "https://attack.mitre.org/techniques/T1547/006",
          pathToMd: `${MBC_BASE_URL}/persistence/kernel-modules-and-extensions.md`,
        },
        {
          id: "B0026",
          name: "Malicious Network Driver",
          description: "Malware installs a malicious network driver.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/persistence/malicious-network-driver.md`,
        },
        {
          id: "F0011",
          name: "Modify Existing Service",
          description: "Malware modifies an existing service for persistence.",
          attackMapping: "T1543.003",
          attackUrl: "https://attack.mitre.org/techniques/T1543/003",
          pathToMd: `${MBC_BASE_URL}/persistence/modify-existing-service.md`,
        },
        {
          id: "E1112",
          name: "Modify Registry",
          description: "Malware modifies the Windows registry.",
          attackMapping: "T1112",
          attackUrl: "https://attack.mitre.org/techniques/T1112",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/modify-registry.md`,
        },
        {
          id: "F0012",
          name: "Registry Run Keys / Startup Folder",
          description: "Malware uses registry run keys or startup folders for persistence.",
          attackMapping: "T1547.001",
          attackUrl: "https://attack.mitre.org/techniques/T1547/001",
          pathToMd: `${MBC_BASE_URL}/persistence/registry-run-keys-startup-folder.md`,
        },
        {
          id: "E1105",
          name: "Ingress Tool Transfer",
          description: "Malware transfers tools or files from an external system into the compromised environment.",
          attackMapping: "T1105",
          attackUrl: "https://attack.mitre.org/techniques/T1105",
          pathToMd: `${MBC_BASE_URL}/command-and-control/ingress-tool-transfer.md`,
        },
        {
          id: "B0035",
          name: "Shutdown Event",
          description: "Malware uses shutdown events for persistence.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/persistence/shutdown-event.md`,
        },
      ]
    },
    {
      objectiveId: "OB0013",
      objectiveName: "Privilege Escalation",
      description: "Behaviors that enable malware to obtain higher level permissions. These behaviors often overlap with Persistence behaviors.",
      behaviors: [
        {
          id: "F0015",
          name: "Hijack Execution Flow",
          description: "Malware may execute by hijacking the way operating systems run programs.",
          attackMapping: "T1574",
          attackUrl: "https://attack.mitre.org/techniques/T1574",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/hijack-execution-flow.md`,
          methods: [
            { id: "F0015.006", name: "Abuse Windows Function Calls" },
            { id: "F0015.001", name: "Export Address Table Hooking" },
            { id: "F0015.003", name: "Import Address Table Hooking" },
            { id: "F0015.002", name: "Inline Patching" },
            { id: "F0015.007", name: "Procedure Hooking" },
            { id: "F0015.004", name: "Shadow System Service Dispatch Table Hooking" },
            { id: "F0015.005", name: "System Service Dispatch Table Hooking" },
          ]
        },
        {
          id: "F0010",
          name: "Kernel Modules and Extensions",
          description: "Malware loads or modifies kernel modules for persistence.",
          attackMapping: "T1547.006",
          attackUrl: "https://attack.mitre.org/techniques/T1547/006",
          pathToMd: `${MBC_BASE_URL}/persistence/kernel-modules-and-extensions.md`,
        },
        {
          id: "F0011",
          name: "Modify Existing Service",
          description: "Malware modifies an existing service for persistence.",
          attackMapping: "T1543.003",
          attackUrl: "https://attack.mitre.org/techniques/T1543/003",
          pathToMd: `${MBC_BASE_URL}/persistence/modify-existing-service.md`,
        },
        {
          id: "E1055",
          name: "Process Injection",
          description: "Malware injects code into processes to evade detection.",
          attackMapping: "T1055",
          attackUrl: "https://attack.mitre.org/techniques/T1055",
          pathToMd: `${MBC_BASE_URL}/defense-evasion/process-injection.md`,
        },
        {
          id: "F0016",
          name: "Install Certificate",
          description: "Malware installs a root certificate to enable man-in-the-middle or evade security checks.",
          attackMapping: null,
          pathToMd: `${MBC_BASE_URL}/privilege-escalation/install-certificate.md`,
        },
      ]
    },
  ],
  microObjectives: [
    {
      objectiveId: "OC0006",
      objectiveName: "Communication",
      description: "Micro-behaviors that enable malware to communicate.",
      behaviors: [
        { id: "C0001", name: "Socket Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/socket-communication.md` },
        { id: "C0002", name: "HTTP Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/http-communication.md` },
        { id: "C0003", name: "Interprocess Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/interprocess-communication.md` },
        { id: "C0004", name: "FTP Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/ftp-communication.md` },
        { id: "C0005", name: "WinINet Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/wininet.md` },
        { id: "C0011", name: "DNS Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/dns-communication.md` },
        { id: "C0012", name: "SMTP Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/smtp-communication.md` },
        { id: "C0014", name: "ICMP Communication", objective: "COMMUNICATION", pathToMd: `${MBC_BASE_URL}/micro-behaviors/communication/icmp-communication.md` },
      ]
    },
    {
      objectiveId: "OC0005",
      objectiveName: "Cryptography",
      description: "Micro-behaviors that enable malware to use cryptography.",
      behaviors: [
        { id: "C0021", name: "Generate Pseudo-random Sequence", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/generate-pseudorandom-sequence.md` },
        { id: "C0027", name: "Encrypt Data", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/encrypt-data.md` },
        { id: "C0028", name: "Encryption Key", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/encryption-key.md` },
        { id: "C0029", name: "Cryptography Hash", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/cryptographic-hash.md` },
        { id: "C0031", name: "Decrypt Data", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/decrypt-data.md` },
        { id: "C0059", name: "Crypto Library", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/crypto-library.md` },
        { id: "C0061", name: "Hashed Message Authentication Code", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/hashed-message-authentication-code.md` },
        { id: "C0068", name: "Crypto Algorithm", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/crypto-algorithm.md` },
        { id: "C0069", name: "Crypto Constant", objective: "CRYPTOGRAPHY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/cryptography/crypto-constant.md` },
      ]
    },
    {
      objectiveId: "OC0004",
      objectiveName: "Data",
      description: "Micro-behaviors related to malware manipulating data.",
      behaviors: [
        { id: "C0019", name: "Check String", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/check-string.md` },
        { id: "C0020", name: "Use Constant", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/use-constant.md` },
        { id: "C0024", name: "Compress Data", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/compress-data.md` },
        { id: "C0025", name: "Decompress Data", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/decompress-data.md` },
        { id: "C0026", name: "Encode Data", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/encode-data.md` },
        { id: "C0030", name: "Non-Cryptographic Hash", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/noncryptographic-hash.md` },
        { id: "C0032", name: "Checksum", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/checksum.md` },
        { id: "C0053", name: "Decode Data", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/decode-data.md` },
        { id: "C0058", name: "Modulo", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/modulo.md` },
        { id: "C0060", name: "Compression Library", objective: "DATA", pathToMd: `${MBC_BASE_URL}/micro-behaviors/data/compression-library.md` },
      ]
    },
    {
      objectiveId: "OC0001",
      objectiveName: "File System",
      description: "Micro-behaviors related to file manipulation.",
      behaviors: [
        { id: "C0015", name: "Alter File Extension", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/alter-file-extension.md` },
        { id: "C0016", name: "Create File", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/create-file.md` },
        { id: "C0045", name: "Copy File", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/copy-file.md` },
        { id: "C0046", name: "Create Directory", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/create-directory.md` },
        { id: "C0047", name: "Delete File", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/delete-file.md` },
        { id: "C0048", name: "Delete Directory", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/delete-directory.md` },
        { id: "C0049", name: "Get File Attributes", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/get-file-attributes.md` },
        { id: "C0050", name: "Set File Attributes", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/set-file-attributes.md` },
        { id: "C0051", name: "Read File", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/read-file.md` },
        { id: "C0052", name: "Writes File", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/writes-file.md` },
        { id: "C0056", name: "Read Virtual Disk", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/read-virtual-disk.md` },
        { id: "C0063", name: "Move File", objective: "FILE SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/file-system/move-file.md` },
      ]
    },
    {
      objectiveId: "OC0007",
      objectiveName: "Hardware",
      description: "Micro-behaviors related to hardware.",
      behaviors: [
        { id: "C0023", name: "Load Driver", objective: "HARDWARE", pathToMd: `${MBC_BASE_URL}/micro-behaviors/hardware/load-driver.md` },
        { id: "C0037", name: "Install Driver", objective: "HARDWARE", pathToMd: `${MBC_BASE_URL}/micro-behaviors/hardware/install-driver.md` },
        { id: "C0057", name: "Simulate Hardware", objective: "HARDWARE", pathToMd: `${MBC_BASE_URL}/micro-behaviors/hardware/simulate-hardware.md` },
      ]
    },
    {
      objectiveId: "OC0002",
      objectiveName: "Memory",
      description: "Micro-behaviors related to malware manipulating machine memory.",
      behaviors: [
        { id: "C0006", name: "Heap Spray", objective: "MEMORY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/memory/heap-spray.md` },
        { id: "C0007", name: "Allocate Memory", objective: "MEMORY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/memory/allocate-memory.md` },
        { id: "C0008", name: "Change Memory Protection", objective: "MEMORY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/memory/change-memory-protection.md` },
        { id: "C0009", name: "Stack Pivot", objective: "MEMORY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/memory/stack-pivot.md` },
        { id: "C0010", name: "Overflow Buffer", objective: "MEMORY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/memory/overflow-buffer.md` },
        { id: "C0044", name: "Free Memory", objective: "MEMORY", pathToMd: `${MBC_BASE_URL}/micro-behaviors/memory/free-memory.md` },
      ]
    },
    {
      objectiveId: "OC0008",
      objectiveName: "Operating System",
      description: "Micro-behaviors related to operating systems.",
      behaviors: [
        { id: "C0033", name: "Console", objective: "OPERATING SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/operating-system/console.md` },
        { id: "C0034", name: "Environment Variable", objective: "OPERATING SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/operating-system/environment-variable.md` },
        { id: "C0035", name: "Wallpaper", objective: "OPERATING SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/operating-system/wallpaper.md` },
        { id: "C0036", name: "Registry", objective: "OPERATING SYSTEM", pathToMd: `${MBC_BASE_URL}/micro-behaviors/operating-system/registry.md` },
      ]
    },
    {
      objectiveId: "OC0003",
      objectiveName: "Process",
      description: "Micro-behaviors related to processes.",
      behaviors: [
        { id: "C0017", name: "Create Process", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/create-process.md` },
        { id: "C0018", name: "Terminate Process", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/terminate-process.md` },
        { id: "C0038", name: "Create Thread", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/create-thread.md` },
        { id: "C0039", name: "Terminate Thread", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/terminate-thread.md` },
        { id: "C0040", name: "Allocate Thread Local Storage", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/allocate-thread-local-storage.md` },
        { id: "C0041", name: "Set Thread Local Storage Value", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/set-thread-local-storage-value.md` },
        { id: "C0042", name: "Create Mutex", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/create-mutex.md` },
        { id: "C0043", name: "Check Mutex", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/check-mutex.md` },
        { id: "C0054", name: "Resume Thread", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/resume-thread.md` },
        { id: "C0055", name: "Suspend Thread", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/suspend-thread.md` },
        { id: "C0064", name: "Enumerate Threads", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/enumerate-threads.md` },
        { id: "C0065", name: "Open Process", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/open-process.md` },
        { id: "C0066", name: "Open Thread", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/open-thread.md` },
        { id: "C0070", name: "Unmap Section View", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/unmap-section-view.md` },
        { id: "C0071", name: "Write Process Memory", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/write-process-memory.md` },
        { id: "C0072", name: "Set Thread Context", objective: "PROCESS", pathToMd: `${MBC_BASE_URL}/micro-behaviors/process/set-thread-context.md` },
      ]
    },
  ]
};

